const EVENT_TYPES = Object.freeze([
  "DEBUGGER_DETECTED",
  "DLL_INJECTION_DETECTED",
  "FOCUS_LOSS_REPEATED",
  "CLIPBOARD_ABUSE_DETECTED",
  "HEARTBEAT_ANOMALY",
  "SESSION_INTEGRITY_FAILURE",
  "KERNEL_TAMPER_SIGNAL",
  "KERNEL_CALLBACK_ANOMALY",
  "PROCESS_STARTED",
  "PROCESS_TERMINATED",
  "PROCESS_POLICY_MATCH",
  "NETWORK_CONNECTION_OBSERVED",
  "NETWORK_POLICY_MATCH",
  "VM_INDICATOR_DETECTED",
  "REMOTE_TOOL_DETECTED",
  "POLICY_ACTION_APPLIED",
  "CLIENT_RUNTIME_ERROR",
  "CLIENT_UPLOAD_STATUS",
  "CLIENT_VERSION_UNSUPPORTED",
  "CLIENT_VERSION_DEPRECATED",
  "CLIENT_VERSION_INVALID",
  "EVENT_IDENTITY_OVERRIDE_APPLIED"
]);

const SEVERITIES = Object.freeze(["low", "medium", "high", "critical"]);

module.exports = {
  EVENT_TYPES,
  SEVERITIES
};
